title:
  german: Mit Zehnern multiplizieren
  english: Multiplying by tens
description: Multiplying by multiples of ten
template: 01_simple_question_answer
fill:
  question:
    german: 'Multipliziere.'
    english: 'Multiply.'
  answer:
    all: <math-field readonly id="equation" class='w-48'></math-field>
pyscript:
  imports: |
    import random
    from pyscript import document
    from pyweb import pydom
    from js import document
  globals: |
    answer = 0
  checker: |
    def check_answer(event):
      # Access the math-field element
      math_field = document.getElementById("equation")
      user_answer = math_field.getPromptValue('answer')
    
      if user_answer.isnumeric():
          user_answer = int(user_answer)
          is_correct = True if user_answer == answer else False
      else:
          is_correct = False

      return [is_correct, answer, user_answer]
  generator: |
    def generate(event):
      global answer

      n1 = random.randint(1, 9) * 10
      n2 = random.randint(1, 9) * 10

      answer = n1 * n2
      equation = f"{n1} \\cdot {n2} = \\placeholder[answer]{{}}"

      mf = document.getElementById("equation")
      mf.setValue(equation)
      mf.mathVirtualKeyboardPolicy = "manual"